baseURL = "https://buildbroken.moonweb.org/"
locale = "de-de"
title = "build broken"
enableRobotsTXT = true
paginate = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "author"

[params]
  subtitle = "but we can fix it! Sometimes :)"
  bannerImage = "/images/banner.jpg"
  description = "build broken – Das Blog-Archiv des .NET-/Softwareentwicklungs-Blogs (2009–2010): Artikel zu Clean Code, ASP.NET, MVC, MVP, WinForms, StupidDB, NoSQL, Scrum und mehr. Von Stefan Kölle, Christina Hirth, Thomas Christian und Andreas Seebauer."

[markup.goldmark.renderer]
  unsafe = true
